name: Node Continues Integration

on:  
 pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test_pull_request:
    runs_on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.17.x'
      - uses: borales/actions-yarn@v3.0.0
        cmd: install # will run `yarn install` command
        cmd: build # will run `yarn build` command
      # - uses: borales/actions-yarn@v3.0.0
      #   with:
      #     cmd: test # will run `yarn test` command